export const weatherIcons = {
    '01d': '../images/icons/clean-sky.png',
    '01n': '../images/icons/night.png',
    '02d': '../images/icons/few-clouds-day.png',
    '02n': '../images/icons/few-clouds-night.png',
    '03d': '../images/icons/clouds.png',
    '03n': '../images/icons/clouds.png',
    '04d': '../images/icons/clouds.png',
    '04n': '../images/icons/clouds.png',
    '09d': '../images/icons/shower-rain.png',
    '09n': '../images/icons/shower-rain.png',
    '10d': '../images/icons/rain.png',
    '10n': '../images/icons/rain.png',
    '11d': '../images/icons/storm.png',
    '11n': '../images/icons/storm.png',
    '13d': '../images/icons/snow.png',
    '13n': '../images/icons/snow.png',
    '50d': '../images/icons/day-mist.png',
    '50n': '../images/icons/night-mist.png',
};