export const weatherImages = {
    '01d': '/images/clear-sky.jpg',
    '01n': '/images/clear-sky-night.jpg',
    '02d': '/images/few-clouds.jpg',
    '02n': '/images/few-clouds-night.jpg',
    '03d': '/images/scattered-clouds.jpg',
    '03n': '/images/scattered-clouds.jpg',
    '04d': '/images/broken-clouds.jpg',
    '04n': '/images/broken-clouds.jpg',
    '09d': '/images/shower-rain.jpg',
    '09n': '/images/shower-rain.jpg',
    '10d': '/images/rain.jpg',
    '10n': '/images/rain.jpg',
    '11d': '/images/thunderstorm.jpg',
    '11n': '/images/thunderstorm.jpg',
    '13d': '/images/snow.jpg',
    '13n': '/images/snow-night.jpg',
    '50d': '/images/mist.jpg',
    '50n': '/images/mist.jpg',
};